# 开始执行脚本前所需执行脚本
before_script:
  - bundle install

# 该ci pipeline适合的场景
stages:
  - test

# 定义的任务1
job1:
  # 场景为构建
  stage: test
  # 所需执行的脚本
  script:
    - python3 ../nornir/nornir_config.py
  # 指定哪个ci runner跑该工作
  tags:
    - shell