# 该ci pipeline适合的场景
stages:
  - install
  - config

job1:
  stage: install
  # 所需执行的脚本
  script:
    - pip3 install -r requirements.txt
  # 指定哪个ci runner跑该工作
  tags:
    - nornir


job2:
  stage: config
  # 所需执行的脚本
  script:
    - python3 nornir_config.py
  # 指定哪个ci runner跑该工作
  tags:
    - nornir