# 该ci pipeline适合的场景
stages:
  - install
  - test

job1:
  # 场景为构建
  stage: install
  # 所需执行的脚本
  script:
    - pip3 install -r requirements.txt
  # 指定哪个ci runner跑该工作
  tags:
    - nornir

# 定义的任务2
job2:
  # 场景为构建
  stage: test
  # 所需执行的脚本
  script:
    - python3 nornir_config.py
  # 指定哪个ci runner跑该工作
  tags:
    - nornir